
================== CRASH DETECTED ==================
Time: 2025-09-09 06:25:40
Runtime: 22659.11 seconds
Exception Type: AttributeError
Exception Value: 'DistanceBasedCachingManager' object has no attribute '_activity_lock'

Traceback:
Traceback (most recent call last):
  File "C:\dcwidget\ui_main.py", line 690, in open_settings_window
    with self.data_manager.user_action_priority():
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\dcwidget\data_manager.py", line 710, in user_action_priority
    self.caching_manager.pause_sync()
  File "C:\dcwidget\data_manager.py", line 431, in pause_sync
    self._activity_lock.lock()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'DistanceBasedCachingManager' object has no attribute '_activity_lock'

================== END CRASH INFO ==================
